import { Exercise, Routine, UserProfile, WorkoutSession } from "./types";

export const DEFAULT_USERS: UserProfile[] = [
  {
    id: "kine-anais",
    name: "Anaïs",
    email: "anais.kine@redreeduc.fr",
    role: "KINE",
    clinicName: "Cabinet de Kinésithérapie & Rééducation du Sport",
  },
  {
    id: "patient-reda",
    name: "Reda",
    email: "reda@redreeduc.fr",
    role: "PATIENT",
    kineId: "kine-anais",
    diagnosis: "Rupture du LCA genou droit (Post-opératoire)",
    medicalHistory: "Ligamentoplastie DIDT effectuée il y a 3 mois.",
    targetGoals: "Récupérer la stabilité et la force du quadriceps sans douleur fémoro-patellaire > 3/10. Reprise du footing.",
  },
];

export const DEFAULT_EXERCISES: Exercise[] = [
  // ==========================================
  // PECTORAUX (POITRINE)
  // ==========================================
  {
    id: "exo-pec-1",
    name: "Développé Couché (Barre)",
    category: "Pectoraux & Dos",
    bodyPart: "Pectoraux, Triceps, Deltoïde Antérieur",
    equipment: "Barre",
    trackingType: "weight_reps",
    defaultRestSeconds: 90,
    instructions: "Allongé sur le banc, pieds au sol, omoplates serrées. Descendre la barre au contact de la poitrine moyenne puis pousser de façon explosive.",
    kineTips: "Ne pas décoller les fesses ni cambrer excessivement. Garder les poignets alignés.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-pec-2",
    name: "Développé Couché (Haltères)",
    category: "Pectoraux & Dos",
    bodyPart: "Pectoraux & Épaules",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 75,
    instructions: "Un haltère dans chaque main au niveau de la poitrine. Développer vers le haut en convergeant légèrement sans claquer les haltères.",
    kineTips: "Excellente liberté articulaire pour les épaules fragiles.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-pec-3",
    name: "Développé Incliné (Haltères)",
    category: "Pectoraux & Dos",
    bodyPart: "Haut des Pectoraux (Claviculaire)",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 75,
    instructions: "Banc incliné à 30-45°. Pousser les haltères vers le haut en contrôlant la trajectoire.",
    kineTips: "Une inclinaison à 30° protège mieux la coiffe des rotateurs qu'à 60°.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-pec-4",
    name: "Presse Pectorale Assise (Machine)",
    category: "Pectoraux & Dos",
    bodyPart: "Pectoraux & Triceps",
    equipment: "Machine",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Assis dos calé, poignées à hauteur de poitrine. Pousser vers l'avant sans verrouiller brutalement les coudes.",
    kineTips: "Idéal en rééducation pour un guidage sécurisé et un contrôle de l'amplitude.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-pec-5",
    name: "Écarté Pectoraux / Butterfly (Machine Pec Deck)",
    category: "Pectoraux & Dos",
    bodyPart: "Grand Pectoral (Isolation)",
    equipment: "Machine",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Bras fléchis sur les coussins ou poignées. Rapprocher les coudes vers l'avant en contractant fort les pectoraux.",
    kineTips: "Ne pas dépasser l'alignement des épaules vers l'arrière pour épargner la capsule antérieure.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-pec-6",
    name: "Écarté à la Poulie Vis-à-Vis",
    category: "Pectoraux & Dos",
    bodyPart: "Pectoraux (Faisceau Moyen & Inférieur)",
    equipment: "Poulie",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Debout, un câble dans chaque main, buste légèrement penché. Rapprocher les mains en arc de cercle vers l'avant.",
    kineTips: "Tension continue excellente pour les tendons.",
    iconName: "Target",
  },
  {
    id: "exo-pec-7",
    name: "Pompes au Sol (Push-ups)",
    category: "Pectoraux & Dos",
    bodyPart: "Pectoraux, Triceps, Gainage",
    equipment: "Poids de corps",
    trackingType: "reps_only",
    defaultRestSeconds: 60,
    instructions: "Mains écartées de la largeur d'épaules, corps droit et gainé. Descendre la poitrine près du sol puis remonter.",
    kineTips: "Option sur les genoux ou mains surélevées si la charge est trop intense.",
    iconName: "Shield",
  },
  {
    id: "exo-pec-8",
    name: "Dips Pectoraux (Barres Parallèles)",
    category: "Pectoraux & Dos",
    bodyPart: "Bas des Pectoraux & Triceps",
    equipment: "Poids de corps",
    trackingType: "weight_reps",
    defaultRestSeconds: 90,
    instructions: "En appui sur les barres, buste légèrement penché en avant. Fléchir les bras jusqu'à 90° de coude puis repousser.",
    kineTips: "Attention si antécédent de luxation antérieure d'épaule.",
    iconName: "Flame",
  },

  // ==========================================
  // DOS & RACHIS
  // ==========================================
  {
    id: "exo-dos-t-1",
    name: "Tractions Prise Pronation (Pull-ups)",
    category: "Dos & Tronc",
    bodyPart: "Grand Dorsal, Trapèzes, Biceps",
    equipment: "Poids de corps",
    trackingType: "reps_only",
    defaultRestSeconds: 90,
    instructions: "Suspendu à la barre fixe, mains plus larges que les épaules. Se tracter jusqu'à amener le menton au-dessus de la barre.",
    kineTips: "Utiliser un élastique de délestage si besoin.",
    iconName: "ArrowUp",
  },
  {
    id: "exo-dos-t-2",
    name: "Tirage Vertical Poitrine (Poulie Haute)",
    category: "Dos & Tronc",
    bodyPart: "Grand Dorsal & Grand Rond",
    equipment: "Machine",
    trackingType: "weight_reps",
    defaultRestSeconds: 75,
    instructions: "Assis cuisses calées, tirer la barre vers le haut de la poitrine en resserrant les omoplates vers le bas.",
    kineTips: "Ne pas tirer derrière la nuque pour préserver les cervicales.",
    iconName: "Target",
  },
  {
    id: "exo-dos-t-3",
    name: "Tirage Horizontal Prise Neutre (Poulie Basse)",
    category: "Dos & Tronc",
    bodyPart: "Rhomboïdes, Trapèzes Moyens, Grand Dorsal",
    equipment: "Poulie",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Pieds calés, dos droit, genoux déverrouillés. Tirer la poignée vers le nombril en serrant fort les omoplates.",
    kineTips: "Garder le buste fixe, pas de balancement d'avant en arrière.",
    iconName: "Repeat",
  },
  {
    id: "exo-dos-t-4",
    name: "Rowing Bûcheron Unilatéral (Haltère)",
    category: "Dos & Tronc",
    bodyPart: "Grand Dorsal & Stabilisateurs Scapulaires",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Un genou et une main en appui sur un banc, dos horizontal. Tirer l'haltère vers la hanche en gardant le coude serré.",
    kineTips: "Excellent pour corriger les asymétries de force gauche/droite.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-dos-t-5",
    name: "Rowing Barre Buste Penché (Barbell Row)",
    category: "Dos & Tronc",
    bodyPart: "Ensemble du Dos & Érecteurs du Rachis",
    equipment: "Barre",
    trackingType: "weight_reps",
    defaultRestSeconds: 90,
    instructions: "Buste incliné à 45°, genoux fléchis, dos cambré naturellement. Tirer la barre vers le bas du ventre.",
    kineTips: "Verrouiller le gainage lombaire tout le long du mouvement.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-dos-t-6",
    name: "Rowing Assis sur Machine Guidée",
    category: "Dos & Tronc",
    bodyPart: "Épaisseur du Dos & Rhomboïdes",
    equipment: "Machine",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Buste appuyé contre le support vertical. Tirer les poignées en arrière en contrôlant la phase excentrique.",
    kineTips: "Très sécurisant pour les lombalgiques (le buste est soutenu).",
    iconName: "Target",
  },
  {
    id: "exo-dos-t-7",
    name: "Soulevé de Terre Conventionnel (Deadlift)",
    category: "Dos & Tronc",
    bodyPart: "Chaîne Postérieure, Fessiers, Ischios, Lombaires",
    equipment: "Barre",
    trackingType: "weight_reps",
    defaultRestSeconds: 120,
    instructions: "Pieds écartés largeur de hanches sous la barre. Pousser sur les jambes en gardant la barre au contact des tibias puis du bassin.",
    kineTips: "Dos neutre obligatoire. Ne jamais arrondir la zone lombaire.",
    iconName: "Flame",
  },
  {
    id: "exo-dos-t-8",
    name: "Soulevé de Terre Roumain (RDL Haltères)",
    category: "Dos & Tronc",
    bodyPart: "Ischio-jambiers & Grands Fessiers",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 75,
    instructions: "Genoux très légèrement fléchis mais fixes. Basculer le bassin en arrière en faisant glisser les haltères le long des cuisses.",
    kineTips: "Sentir l'étirement actif des ischios sans cambrer.",
    iconName: "Activity",
  },
  {
    id: "exo-dos-t-9",
    name: "Pull-over avec Haltère",
    category: "Dos & Tronc",
    bodyPart: "Grand Dorsal, Pectoraux, Dentelé",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Allongé sur le banc en travers, haltère tenu à deux mains. Descendre l'haltère derrière la tête bras semi-fléchis puis remonter.",
    kineTips: "Ouvre la cage thoracique et mobilise les épaules en extension.",
    iconName: "Dumbbell",
  },

  // ==========================================
  // ÉPAULES & COIFFE DES ROTATEURS
  // ==========================================
  {
    id: "exo-epaule-m-1",
    name: "Développé Militaire Debout (Barre OHP)",
    category: "Épaule",
    bodyPart: "Deltoïdes & Stabilité Tronc",
    equipment: "Barre",
    trackingType: "weight_reps",
    defaultRestSeconds: 90,
    instructions: "Debout, barre clavicules. Pousser la barre au-dessus de la tête jusqu'au verrouillage en engageant la tête vers l'avant.",
    kineTips: "Serrer fessiers et abdos pour ne pas cambrer le bas du dos.",
    iconName: "ArrowUp",
  },
  {
    id: "exo-epaule-m-2",
    name: "Développé Épaules Assis (Haltères)",
    category: "Épaule",
    bodyPart: "Deltoïdes Antérieurs & Moyens",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 75,
    instructions: "Assis sur banc à 80°, haltères au niveau des oreilles. Pousser verticalement sans toucher les haltères en haut.",
    kineTips: "Descendre jusqu'à ce que les bras soient parallèles au sol.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-epaule-m-3",
    name: "Développé Épaules Guidé (Machine)",
    category: "Épaule",
    bodyPart: "Deltoïdes",
    equipment: "Machine",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Assis dos au dossier, poignées réglées à hauteur d'épaules. Pousser de manière fluide et contrôlée.",
    kineTips: "Parfait pour isoler le travail des épaules sans contrainte d'équilibre.",
    iconName: "Target",
  },
  {
    id: "exo-epaule-m-4",
    name: "Élévations Latérales (Haltères)",
    category: "Épaule",
    bodyPart: "Deltoïde Moyen (Largeur d'épaules)",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Debout ou assis, coudes légèrement déverrouillés. Élever les bras sur les côtés dans le plan de l'omoplate (30° vers l'avant).",
    kineTips: "Garder les trapèzes relâchés pour ne pas hausser les épaules.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-epaule-m-5",
    name: "Élévations Latérales à la Poulie Basse",
    category: "Épaule",
    bodyPart: "Deltoïde Moyen (Tension continue)",
    equipment: "Poulie",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Câble pris en arrière du corps ou devant, monter la poignée jusqu'à l'horizontale.",
    kineTips: "Tension maximale dès le départ du mouvement.",
    iconName: "Target",
  },
  {
    id: "exo-epaule-m-6",
    name: "Oiseau Buste Penché / Banc Incliné (Haltères)",
    category: "Épaule",
    bodyPart: "Deltoïde Postérieur & Fixateurs d'omoplates",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Buste appuyé sur banc à 45°. Écarter les bras vers l'extérieur en rapprochant les omoplates.",
    kineTips: "Fondamental pour l'équilibre postural et la prévention des conflits d'épaule.",
    iconName: "Eye",
  },
  {
    id: "exo-epaule-m-7",
    name: "Face Pull à la Poulie Haute (Corde)",
    category: "Épaule",
    bodyPart: "Rotateurs Externes, Deltoïde Postérieur, Trapèze Moyen",
    equipment: "Poulie",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Tirer la corde vers le front en écartant les mains et en finissant les pouces tournés vers l'arrière.",
    kineTips: "L'un des meilleurs exercices de kinésithérapie préventive d'épaule.",
    iconName: "RotateCw",
  },
  {
    id: "exo-epaule-m-8",
    name: "Rotateurs Externes à l'Élastique (Coude au corps)",
    category: "Épaule",
    bodyPart: "Coiffe des rotateurs (Sous-épineux)",
    equipment: "Élastique",
    trackingType: "elastic_reps",
    defaultRestSeconds: 45,
    instructions: "Coude collé aux côtes fléchi à 90°, petite serviette sous le coude. Ouvrir l'avant-bras vers l'extérieur.",
    kineTips: "Mouvement lent, 0 douleur permise.",
    iconName: "RotateCw",
  },
  {
    id: "exo-epaule-m-9",
    name: "Wall Slide Scapulaire au Mur",
    category: "Épaule",
    bodyPart: "Dentelé Antérieur & Trapèze Inférieur",
    equipment: "Poids de corps",
    trackingType: "reps_only",
    defaultRestSeconds: 45,
    instructions: "Avant-bras au mur en 'W', glisser lentement vers le haut en 'Y' sans décoller le contact mural.",
    kineTips: "Garder le ventre rentré et la tête droite.",
    iconName: "ArrowUp",
  },

  // ==========================================
  // BRAS : BICEPS & TRICEPS
  // ==========================================
  {
    id: "exo-bras-b-1",
    name: "Curl Biceps debout (Barre EZ)",
    category: "Bras",
    bodyPart: "Biceps Brachial & Brachial Antérieur",
    equipment: "Barre",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Debout, coudes calés contre les flancs. Monter la barre en fléchissant les avant-bras, descente lente en 2s.",
    kineTips: "La courbure de la barre EZ soulage les poignets et le coude.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-bras-b-2",
    name: "Curl Biceps Alterné avec Supination (Haltères)",
    category: "Bras",
    bodyPart: "Biceps Brachial",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Départ prise neutre, tourner la paume vers le haut pendant la montée (supination complète).",
    kineTips: "Contrôler la descente sans balancer le buste.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-bras-b-3",
    name: "Curl Marteau (Haltères)",
    category: "Bras",
    bodyPart: "Brachio-radial & Long Supinateur",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Prise neutre constante (pouces vers le haut). Monter l'haltère de façon stricte.",
    kineTips: "Excellent pour stabiliser le coude et renforcer l'avant-bras.",
    iconName: "Hammer",
  },
  {
    id: "exo-bras-b-4",
    name: "Curl Incliné sur Banc (Haltères)",
    category: "Bras",
    bodyPart: "Longue Portion du Biceps",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Assis sur banc incliné à 60°, bras pendants en arrière. Fléchir sans avancer les coudes.",
    kineTips: "Éirement maximal en bas du mouvement.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-bras-b-5",
    name: "Curl Pupitre Larry Scott (Machine / Barre)",
    category: "Bras",
    bodyPart: "Courte Portion du Biceps (Isolation)",
    equipment: "Machine",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Bras calés sur le pupitre incliné. Fléchir les avant-bras, descente contrôlée.",
    kineTips: "Ne pas tendre complètement le bras en bas pour préserver le tendon du biceps.",
    iconName: "Target",
  },
  {
    id: "exo-bras-t-1",
    name: "Extension Triceps Poulie Haute (Corde)",
    category: "Bras",
    bodyPart: "Vaste Externe & Triceps",
    equipment: "Poulie",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Coudes verrouillés aux flancs. Pousser la corde vers le bas en écartant les pointes en bas.",
    kineTips: "Garder les épaules basses et les coudes immobiles.",
    iconName: "Target",
  },
  {
    id: "exo-bras-t-2",
    name: "Barre au Front / Skull Crushers (Barre EZ)",
    category: "Bras",
    bodyPart: "Longue Portion du Triceps",
    equipment: "Barre",
    trackingType: "weight_reps",
    defaultRestSeconds: 75,
    instructions: "Allongé sur le banc, bras verticaux. Fléchir uniquement les coudes pour descendre la barre vers le front puis repousser.",
    kineTips: "Si douleur au coude, privilégier des haltères en prise neutre.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-bras-t-3",
    name: "Dips entre Deux Bancs (Poids de corps)",
    category: "Bras",
    bodyPart: "Triceps & Épaules",
    equipment: "Poids de corps",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Mains sur un banc derrière le dos, pieds sur un banc en face ou au sol. Descendre les fesses en fléchissant les coudes.",
    kineTips: "Garder le dos proche du bord du banc.",
    iconName: "Activity",
  },

  // ==========================================
  // JAMBES & FESSIERS (MEMBRES INFÉRIEURS)
  // ==========================================
  {
    id: "exo-jambe-1",
    name: "Squat Arrière (Barre Nuque / Back Squat)",
    category: "Genou",
    bodyPart: "Quadriceps, Fessiers, Ischios",
    equipment: "Barre",
    trackingType: "weight_reps",
    defaultRestSeconds: 120,
    instructions: "Barre sur les trapèzes, pieds écartés largeur d'épaules. Descendre le bassin en poussant les genoux vers l'extérieur puis remonter en poussant dans les talons.",
    kineTips: "Trajectoire des genoux bien alignée avec le 2e orteil. Descente contrôlée.",
    iconName: "Flame",
  },
  {
    id: "exo-jambe-2",
    name: "Goblet Squat (Kettlebell / Haltère)",
    category: "Genou",
    bodyPart: "Quadriceps & Mobilité de Cheville",
    equipment: "Kettlebell",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Tenir la kettlebell contre la poitrine à deux mains. Descendre en squat profond en gardant le buste très droit.",
    kineTips: "Exercice roi en rééducation du genou pour apprendre à squatter sans contrainte lombaire.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-jambe-3",
    name: "Presse à Cuisses Inclinée (Machine)",
    category: "Genou",
    bodyPart: "Quadriceps, Fessiers",
    equipment: "Machine",
    trackingType: "weight_reps",
    defaultRestSeconds: 90,
    instructions: "Pieds sur le plateau, descente contrôlée en 3s jusqu'à 90° de flexion, poussée dynamique sans verrouiller les genoux.",
    kineTips: "Permet de charger les quadriceps en épargnant complètement le dos.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-jambe-4",
    name: "Hack Squat (Machine Guidée)",
    category: "Genou",
    bodyPart: "Quadriceps (Focalisation Vaste Interne)",
    equipment: "Machine",
    trackingType: "weight_reps",
    defaultRestSeconds: 90,
    instructions: "Dos calé sur le dossier incliné, pieds en bas du plateau. Descendre en flexion puis remonter.",
    kineTips: "Contrôler la descente sans rebond en bas.",
    iconName: "Flame",
  },
  {
    id: "exo-jambe-5",
    name: "Fentes Bulgares (Haltères / Poids de corps)",
    category: "Genou",
    bodyPart: "Quadriceps, Grand Fessier, Stabilité Cheville",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Un pied posé sur un banc derrière soi, l'autre jambe devant. Descendre le genou arrière vers le sol et remonter sur le talon avant.",
    kineTips: "Travail unilatéral indispensable après une chirurgie du LCA pour rattraper le déficit.",
    iconName: "Activity",
  },
  {
    id: "exo-jambe-6",
    name: "Fentes Avant Marchées (Haltères)",
    category: "Genou",
    bodyPart: "Quadriceps & Fessiers",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Avancer d'un grand pas, descendre le genou arrière à quelques centimètres du sol, puis enchaîner avec la jambe suivante.",
    kineTips: "Garder le buste droit et le genou avant stable sans valgus.",
    iconName: "Footprints",
  },
  {
    id: "exo-jambe-7",
    name: "Leg Extension Guidé (Machine)",
    category: "Genou",
    bodyPart: "Quadriceps (Chaîne ouverte)",
    equipment: "Machine",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Assis dos calé, manchon au-dessus des chevilles. Tendre les jambes en marquant un temps d'arrêt de 1s en haut.",
    kineTips: "En post-opératoire LCA, limiter l'amplitude entre 90° et 45° selon prescription du praticien.",
    iconName: "Zap",
  },
  {
    id: "exo-jambe-8",
    name: "Leg Curl Couché (Machine Ischios)",
    category: "Genou",
    bodyPart: "Ischio-jambiers",
    equipment: "Machine",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Allongé sur le ventre, manchon calé sous les mollets. Fléchir les jambes pour amener les talons vers les fessiers.",
    kineTips: "Essentiel pour rééquilibrer le ratio ischio-jambiers / quadriceps (I/Q).",
    iconName: "Activity",
  },
  {
    id: "exo-jambe-9",
    name: "Hip Thrust (Barre au Bassin / Machine)",
    category: "Hanche",
    bodyPart: "Grand Fessier (Puissance & Extension)",
    equipment: "Barre",
    trackingType: "weight_reps",
    defaultRestSeconds: 90,
    instructions: "Haut du dos sur un banc, barre rembourrée sur les hanches, tibias verticaux en haut. Monter le bassin à l'horizontale en contractant les fessiers.",
    kineTips: "Rétroversion du bassin en haut sans cambrer les lombaires.",
    iconName: "Flame",
  },
  {
    id: "exo-jambe-10",
    name: "Chaise au Mur (Isométrie Quadriceps)",
    category: "Genou",
    bodyPart: "Quadriceps & Rotule",
    equipment: "Poids de corps / Mur",
    trackingType: "time",
    defaultRestSeconds: 60,
    instructions: "Dos plaqué au mur, cuisses horizontales à 90°, pieds à plat. Tenir la position immobile.",
    kineTips: "Stimule les fibres tendineuses sans frottement articulaire (idéal tendinite rotulienne).",
    iconName: "Shield",
  },
  {
    id: "exo-jambe-11",
    name: "Pont Fessier Unipodal (Glute Bridge)",
    category: "Genou",
    bodyPart: "Grand Fessier & Stabilisateurs",
    equipment: "Poids de corps",
    trackingType: "reps_only",
    defaultRestSeconds: 45,
    instructions: "Allongé sur le dos, un pied au sol, l'autre jambe levée. Monter le bassin en poussant sur le talon.",
    kineTips: "Bassin horizontal, ne pas laisser la hanche pencher du côté libre.",
    iconName: "Activity",
  },
  {
    id: "exo-jambe-12",
    name: "Mollets Debout sur Marche (Calf Raises)",
    category: "Cheville & Pied",
    bodyPart: "Triceps Sural & Tendon d'Achille",
    equipment: "Machine",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Pointe des pieds sur la cale, talons dans le vide. Monter le plus haut possible sur la pointe des pieds, descendre lentement sous le niveau de la marche.",
    kineTips: "Temps d'arrêt de 2s en position basse étirée.",
    iconName: "TrendingUp",
  },
  {
    id: "exo-jambe-13",
    name: "Mollets Assis (Machine Soleus)",
    category: "Cheville & Pied",
    bodyPart: "Soléaire (Muscle profond du mollet)",
    equipment: "Machine",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Assis genoux à 90°, manchon sur les cuisses. Extension des chevilles.",
    kineTips: "Le soléaire absorbe jusqu'à 8 fois le poids du corps lors de la course.",
    iconName: "TrendingUp",
  },
  {
    id: "exo-jambe-14",
    name: "Machine Abducteurs Assis",
    category: "Hanche",
    bodyPart: "Moyen Fessier & Tenseur du Fascia Lata",
    equipment: "Machine",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Assis, coussins à l'extérieur des genoux. Écarter les cuisses en maintenant 1s en fin de course.",
    kineTips: "Renforce la stabilité pelvienne pour empêcher le valgus du genou à la marche.",
    iconName: "Target",
  },
  {
    id: "exo-jambe-15",
    name: "Clamshell avec Élastique",
    category: "Hanche",
    bodyPart: "Moyen Fessier (Rotation externe)",
    equipment: "Élastique",
    trackingType: "elastic_reps",
    defaultRestSeconds: 45,
    instructions: "Couché sur le côté, genoux à 90°, élastique au-dessus des genoux. Ouvrir le genou supérieur en gardant les pieds en contact.",
    kineTips: "Ne pas rouler le bassin vers l'arrière.",
    iconName: "Repeat",
  },

  // ==========================================
  // KETTLEBELL (CONDITIONING & FORCE)
  // ==========================================
  {
    id: "exo-kb-1",
    name: "Kettlebell Swing (Style Russe)",
    category: "Dos & Tronc",
    bodyPart: "Chaîne Postérieure, Fessiers, Énergie Cardiovasculaire",
    equipment: "Kettlebell",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Balancement balistique initié par la charnière de hanche (hip hinge). Projeter la kettlebell à hauteur de poitrine grâce à la contraction des fessiers.",
    kineTips: "Ce sont les hanches qui propulsent, pas les bras ni les lombaires.",
    iconName: "Flame",
  },
  {
    id: "exo-kb-2",
    name: "Kettlebell Clean & Press",
    category: "Épaule",
    bodyPart: "Épaules, Triceps, Hanches",
    equipment: "Kettlebell",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Épaulé de la kettlebell au niveau de la clavicule puis développé militaire vertical au-dessus de la tête.",
    kineTips: "Contrôler la réception de la cloche sans heurter l'avant-bras.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-kb-3",
    name: "Turkish Get-Up / Relevé Turc (Kettlebell)",
    category: "Épaule",
    bodyPart: "Stabilité Globale, Épaules, Gainage",
    equipment: "Kettlebell",
    trackingType: "weight_reps",
    defaultRestSeconds: 75,
    instructions: "Allongé au sol, bras tendu vertical avec la kettlebell. Se relever jusqu'à la position debout puis redescendre sans quitter la cloche du regard.",
    kineTips: "Exercice roi pour la proprioception et la stabilité 3D de l'épaule.",
    iconName: "Shield",
  },
  {
    id: "exo-kb-4",
    name: "Marche du Fermier / Farmer's Walk (Kettlebells)",
    category: "Dos & Tronc",
    bodyPart: "Grip / Poigne, Trapèzes, Gainage Anti-latéroflexion",
    equipment: "Kettlebell",
    trackingType: "time",
    defaultRestSeconds: 60,
    instructions: "Une kettlebell lourde dans chaque main, marcher d'un pas droit et régulier sans osciller.",
    kineTips: "Garder les épaules reculées et le regard au loin.",
    iconName: "Footprints",
  },
  {
    id: "exo-kb-5",
    name: "Kettlebell Halo (Mobilité Scapulaire)",
    category: "Épaule",
    bodyPart: "Mobilité des Épaules & Sangle Abdominale",
    equipment: "Kettlebell",
    trackingType: "weight_reps",
    defaultRestSeconds: 45,
    instructions: "Kettlebell tenue par les cornes à l'envers devant le menton. Faire tourner la cloche autour de la tête en cercle serré.",
    kineTips: "Garder la tête fixe, ce sont les bras qui tournent.",
    iconName: "RotateCw",
  },

  // ==========================================
  // ABDOMINAUX & GAINAGE DU RACHIS
  // ==========================================
  {
    id: "exo-abdo-1",
    name: "Gainage Planche Ventrale (Plank)",
    category: "Dos & Tronc",
    bodyPart: "Transverse & Stabilité Pelvienne",
    equipment: "Poids de corps",
    trackingType: "time",
    defaultRestSeconds: 45,
    instructions: "En appui sur les avant-bras et la pointe des pieds, corps droit comme une flèche, nombril aspiré vers la colonne.",
    kineTips: "Ne pas laisser les fesses descendre ni monter.",
    iconName: "Shield",
  },
  {
    id: "exo-abdo-2",
    name: "Gainage Latéral (Side Plank)",
    category: "Dos & Tronc",
    bodyPart: "Obliques & Carré des Lombes",
    equipment: "Poids de corps",
    trackingType: "time",
    defaultRestSeconds: 45,
    instructions: "En appui sur un avant-bras et la tranche externe du pied. Aligner chevilles, genoux, hanches et tête.",
    kineTips: "Essentiel pour stabiliser le bassin pendant la foulée.",
    iconName: "Activity",
  },
  {
    id: "exo-abdo-3",
    name: "Bird Dog (Chien d'Arrêt Croisé)",
    category: "Dos & Tronc",
    bodyPart: "Érecteurs du Rachis, Fessiers, Transverse",
    equipment: "Poids de corps",
    trackingType: "reps_only",
    defaultRestSeconds: 45,
    instructions: "À quatre pattes, tendre en simultané le bras droit et la jambe gauche à l'horizontale. Maintenir 3s puis alterner.",
    kineTips: "Le bassin reste parfaitement parallèle au sol.",
    iconName: "Smile",
  },
  {
    id: "exo-abdo-4",
    name: "Dead Bug (Insecte Mort)",
    category: "Dos & Tronc",
    bodyPart: "Transverse & Anti-Extension Lombaire",
    equipment: "Poids de corps",
    trackingType: "reps_only",
    defaultRestSeconds: 45,
    instructions: "Sur le dos, genoux à 90°, bras vers le plafond. Tendre un bras derrière et la jambe opposée devant sans décoller les lombaires du sol.",
    kineTips: "Plaquer le bas du dos au sol pendant tout le mouvement.",
    iconName: "Shield",
  },
  {
    id: "exo-abdo-5",
    name: "Roue Abdominale (Ab Wheel Rollout)",
    category: "Dos & Tronc",
    bodyPart: "Grand Droit & Transverse (Anti-extension)",
    equipment: "Poids de corps",
    trackingType: "reps_only",
    defaultRestSeconds: 60,
    instructions: "À genoux sur un tapis, faire rouler la roue vers l'avant le plus loin possible sans creuser les lombaires puis revenir.",
    kineTips: "Exercice avancé : arrêter le mouvement dès que les lombaires menacent de cambrer.",
    iconName: "Target",
  },
  {
    id: "exo-abdo-6",
    name: "Relevé de Jambes Suspendu à la Barre",
    category: "Dos & Tronc",
    bodyPart: "Bas des Abdos & Fléchisseurs de Hanche",
    equipment: "Poids de corps",
    trackingType: "reps_only",
    defaultRestSeconds: 60,
    instructions: "Suspendu à la barre fixe, monter les genoux ou les jambes tendues jusqu'à l'horizontale en enroulant le bassin.",
    kineTips: "Éviter tout balancement du corps.",
    iconName: "ArrowUp",
  },

  // ==========================================
  // CARDIO & PROPRIOCEPTION
  // ==========================================
  {
    id: "exo-cardio-t-1",
    name: "Tapis de Course (Marche Inclinée / Course)",
    category: "Cardio & Échauffement",
    bodyPart: "Système Cardio-Vasculaire & Endurance",
    equipment: "Machine",
    trackingType: "distance_time",
    defaultRestSeconds: 0,
    instructions: "Marche rapide inclinée à 5-8% ou footing à cadence maîtrisée selon l'étape du protocole.",
    kineTips: "Garder une attaque médio-pied douce sans chocs violents sur le talon.",
    iconName: "Footprints",
  },
  {
    id: "exo-cardio-t-2",
    name: "Vélo Stationnaire (Rodage Articulaire)",
    category: "Cardio & Échauffement",
    bodyPart: "Genoux, Hanches & Endurance Aérobie",
    equipment: "Machine",
    trackingType: "time",
    defaultRestSeconds: 0,
    instructions: "Pédalage fluide à 70-80 RPM avec une résistance progressive.",
    kineTips: "Régler la selle de façon à avoir une très légère flexion du genou en bas de pédalage.",
    iconName: "Bike",
  },
  {
    id: "exo-cardio-t-3",
    name: "Rameur Concept2 (Rowing Ergometer)",
    category: "Cardio & Échauffement",
    bodyPart: "Full-Body (Poussée jambes, tirage dos & bras)",
    equipment: "Machine",
    trackingType: "distance_time",
    defaultRestSeconds: 0,
    instructions: "Pousser fort avec les jambes, basculer le buste en arrière puis tirer avec les bras.",
    kineTips: "Ne pas arrondir le dos au départ sur l'attaque.",
    iconName: "Repeat",
  },
  {
    id: "exo-cardio-t-4",
    name: "Plateau de Freeman (Proprioception Unipodale)",
    category: "Cheville & Pied",
    bodyPart: "Mécanorécepteurs Cheville & Genou",
    equipment: "Plateau d'équilibre",
    trackingType: "time",
    defaultRestSeconds: 45,
    instructions: "En appui sur un seul pied au centre du plateau, genou légèrement déverrouillé. Stabiliser le plateau à l'horizontale.",
    kineTips: "Fixer un point au loin. Yeux fermés pour un niveau supérieur.",
    iconName: "Compass",
  },
  {
    id: "exo-cardio-t-5",
    name: "Corde à Sauter",
    category: "Cardio & Échauffement",
    bodyPart: "Mollets, Réactivité Pied & Cardio",
    equipment: "Poids de corps",
    trackingType: "time",
    defaultRestSeconds: 45,
    instructions: "Sauts légers sur la pointe des pieds en tournant les poignets de façon rythmée.",
    kineTips: "Reprise des impacts en phase terminale de rééducation.",
    iconName: "Activity",
  },

  // ==========================================
  // MACHINES GUIDÉES SUPPLÉMENTAIRES
  // ==========================================
  {
    id: "exo-mach-1",
    name: "Presse à Cuisses Horizontale (Machine)",
    category: "Genou",
    bodyPart: "Quadriceps & Fessiers",
    equipment: "Machine",
    trackingType: "weight_reps",
    defaultRestSeconds: 75,
    instructions: "Assis dos au dossier, pieds écartés largeur d'épaules sur le plateau. Pousser en dépliant les genoux sans les verrouiller.",
    kineTips: "Permet de doser très précisément la flexion du genou en limitant les contraintes axiales.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-mach-2",
    name: "Machine Adducteurs Assis",
    category: "Hanche",
    bodyPart: "Adducteurs de Hanche",
    equipment: "Machine",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Assis dos droit, jambes écartées. Resserrer les cuisses vers l'intérieur avec un mouvement fluide et contrôlé.",
    kineTips: "Important pour la stabilité médiale du genou et du bassin.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-mach-3",
    name: "Machine Ischios Assis (Seated Leg Curl)",
    category: "Genou",
    bodyPart: "Ischio-jambiers",
    equipment: "Machine",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Assis cuisses calées, boudin derrière les chevilles. Fléchir les genoux vers l'arrière en contrôlant la phase excentrique.",
    kineTips: "Excellent recrutement des ischio-jambiers en position de pré-étirement de la hanche.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-mach-4",
    name: "Machine Fessiers Kickback (Glute Machine)",
    category: "Hanche",
    bodyPart: "Grand Fessier",
    equipment: "Machine",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "En appui sur le support, pousser le plateau vers l'arrière avec le talon en contractant fort le fessier.",
    kineTips: "Garder le bassin fixe, ne pas cambrer la région lombaire pendant la poussée.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-mach-5",
    name: "Machine Développé Décliné Pectoraux",
    category: "Pectoraux & Dos",
    bodyPart: "Faisceau Inférieur des Pectoraux",
    equipment: "Machine",
    trackingType: "weight_reps",
    defaultRestSeconds: 75,
    instructions: "Assis buste légèrement décliné, pousser les poignées vers l'avant et le bas sans forcer sur la capsule articulaire.",
    kineTips: "Trajectoire très douce pour l'acromio-claviculaire.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-mach-6",
    name: "Tirage Poitrine Guidé Prise Neutre (Lat Pulldown Machine)",
    category: "Dos & Tronc",
    bodyPart: "Grand Dorsal & Trapèzes",
    equipment: "Machine",
    trackingType: "weight_reps",
    defaultRestSeconds: 75,
    instructions: "Poignées neutres face à face. Tirer vers le haut de la poitrine en abaissant et en serrant les omoplates.",
    kineTips: "La prise neutre préserve le tendon du long biceps.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-mach-7",
    name: "Smith Machine Squat (Cadre Guidé)",
    category: "Genou",
    bodyPart: "Quadriceps & Chaîne Postérieure",
    equipment: "Machine",
    trackingType: "weight_reps",
    defaultRestSeconds: 90,
    instructions: "Pieds légèrement avancés par rapport à la barre guidée. Descendre en flexion contrôlée jusqu'à la parallèle.",
    kineTips: "La trajectoire guidée réduit les besoins d'équilibration pour cibler la force pure.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-mach-8",
    name: "Smith Machine Développé Couché",
    category: "Pectoraux & Dos",
    bodyPart: "Pectoraux & Triceps",
    equipment: "Machine",
    trackingType: "weight_reps",
    defaultRestSeconds: 90,
    instructions: "Allongé sur le banc sous la barre guidée, descendre la barre au contact de la poitrine moyenne et remonter.",
    kineTips: "Les crans de sécurité permettent de travailler en charge sans risque de blocage.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-mach-9",
    name: "Smith Machine Fentes Arrière",
    category: "Genou",
    bodyPart: "Quadriceps & Fessiers",
    equipment: "Machine",
    trackingType: "weight_reps",
    defaultRestSeconds: 75,
    instructions: "Sous la barre guidée, reculer une jambe en fente arrière, genou avant fléchi à 90°, puis repousser sur le talon avant.",
    kineTips: "Guidage parfait pour réhabituer le genou aux fentes unipodales.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-mach-10",
    name: "Machine Mollets Debout Guidée",
    category: "Cheville & Pied",
    bodyPart: "Gastrocnémiens (Mollets)",
    equipment: "Machine",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Épaules calées sous les coussins, avant des pieds sur la cale. Descendre les talons pour étirer puis monter sur la pointe.",
    kineTips: "Maintenir 1 seconde de pause en bas pour limiter le rebond tendineux.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-mach-11",
    name: "Machine Crunch Abdominaux Guidée",
    category: "Dos & Tronc",
    bodyPart: "Grand Droit de l'Abdomen",
    equipment: "Machine",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Assis, coudes calés ou poignées en main. Enrouler le buste vers les cuisses en expirant profondément.",
    kineTips: "Enrouler le haut de la colonne sans tirer avec les bras.",
    iconName: "Target",
  },
  {
    id: "exo-mach-12",
    name: "Extension Lombaire sur Banc à 45°",
    category: "Dos & Tronc",
    bodyPart: "Érecteurs du Rachis & Fessiers",
    equipment: "Poids de corps",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Bassin calé sur le coussin, chevilles bloquées. Descendre le buste puis remonter dans l'alignement sans hyper-extension.",
    kineTips: "Ne jamais cambrer au-delà de l'alignement tronc-cuisses.",
    iconName: "Target",
  },

  // ==========================================
  // HALTÈRES (DUMBBELLS) SUPPLÉMENTAIRES
  // ==========================================
  {
    id: "exo-halt-1",
    name: "Développé Décliné (Haltères)",
    category: "Pectoraux & Dos",
    bodyPart: "Bas des Pectoraux",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 75,
    instructions: "Sur banc décliné, développer les haltères au-dessus de la partie basse des pectoraux.",
    kineTips: "Soulage la pression sur la capsule supérieure de l'épaule.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-halt-2",
    name: "Écarté Couché sur Banc Plat (Haltères)",
    category: "Pectoraux & Dos",
    bodyPart: "Pectoraux (Étirement)",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Bras légèrement fléchis, ouvrir les bras sur les côtés jusqu'à sentir l'étirement pectoral, puis refermer.",
    kineTips: "Garder une flexion légère et constante des coudes pour protéger les tendons.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-halt-3",
    name: "Écarté Incliné sur Banc (Haltères)",
    category: "Pectoraux & Dos",
    bodyPart: "Haut des Pectoraux",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Banc à 30°, ouvrir les bras latéralement avec les coudes semi-fléchis, remonter en arc de cercle.",
    kineTips: "Privilégier une charge légère pour préserver l'insertion antérieure du deltoïde.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-halt-4",
    name: "Développé Arnold (Haltères)",
    category: "Épaule",
    bodyPart: "Deltoïdes (Antérieur & Latéral)",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 75,
    instructions: "Départ paumes vers soi au niveau du menton. Développer vers le haut en effectuant une rotation à 180° des poignets.",
    kineTips: "Excellent travail de rotation dynamique pour le complexe de l'épaule.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-halt-5",
    name: "Élévations Frontales (Haltères)",
    category: "Épaule",
    bodyPart: "Deltoïde Antérieur",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Debout ou assis, lever les haltères devant soi jusqu'à la hauteur des épaules, bras quasi tendus.",
    kineTips: "Ne pas balancer le buste, contrôler la descente.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-halt-6",
    name: "Shrugs Trapèzes aux Haltères",
    category: "Dos & Tronc",
    bodyPart: "Trapèzes Supérieurs",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Un haltère lourd dans chaque main le long du corps. Hausser les épaules verticalement vers les oreilles.",
    kineTips: "Ne pas rouler les épaules vers l'avant ou l'arrière pour préserver le labrum.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-halt-7",
    name: "Kickback Triceps à l'Haltère",
    category: "Bras",
    bodyPart: "Triceps (Chef Long)",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Buste penché en appui sur un banc, coude calé le long du corps. Tendre le bras vers l'arrière.",
    kineTips: "Garder le coude immobile pendant toute l'extension.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-halt-8",
    name: "Extension Triceps à Deux Mains au-dessus de la tête",
    category: "Bras",
    bodyPart: "Triceps Brachial",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Assis dos droit, tenir un haltère à deux mains derrière la nuque. Tendre les bras vers le haut.",
    kineTips: "Garder les coudes serrés vers l'avant sans écarter les bras.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-halt-9",
    name: "Curl Biceps Prise Marteau Incliné",
    category: "Bras",
    bodyPart: "Brachio-radial & Biceps",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Assis sur banc incliné à 60°, fléchir les avant-bras avec les paumes face à face.",
    kineTips: "Renforce la chaîne fléchisseuse et l'avant-bras.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-halt-10",
    name: "Curl Concentration Assis",
    category: "Bras",
    bodyPart: "Pic du Biceps Brachial",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Assis coude calé contre la face interne de la cuisse. Enrouler l'haltère vers l'épaule.",
    kineTips: "Élimine tout élan et isole parfaitement le biceps.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-halt-11",
    name: "Fentes Arrière avec Haltères",
    category: "Genou",
    bodyPart: "Quadriceps & Fessiers",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 75,
    instructions: "Debout avec un haltère dans chaque main. Faire un pas en arrière et descendre le genou arrière à 1cm du sol.",
    kineTips: "La fente arrière génère moins de cisaillement rotulien que la fente avant.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-halt-12",
    name: "Step-Up sur Banc avec Haltères",
    category: "Genou",
    bodyPart: "Quadriceps, Fessiers & Stabilité Rotulienne",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 75,
    instructions: "Un pied posé sur une marche ou un banc, monter en poussant fermement sur la jambe d'appui.",
    kineTips: "Contrôler la descente sans s'écraser au sol. Excellent pour le genou opéré.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-halt-13",
    name: "Soulevé de Terre Jambes Tendues (Haltères)",
    category: "Hanche",
    bodyPart: "Ischio-jambiers & Fessiers",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 75,
    instructions: "Genoux très légèrement déverrouillés, basculer le bassin en arrière en gardant le dos neutre.",
    kineTips: "Sentir la tension dans les ischio-jambiers sans arrondir le bas du dos.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-halt-14",
    name: "Mollets Debout Unilatéral à l'Haltère",
    category: "Cheville & Pied",
    bodyPart: "Gastrocnémiens & Soléaire",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Sur une marche, une main tient un haltère, l'autre assure l'équilibre. Monter sur la pointe du pied.",
    kineTips: "Exercice clé pour la propulsion du pied et la rééducation post-entorse ou tendon d'Achille.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-halt-15",
    name: "Russian Twist avec Haltère",
    category: "Dos & Tronc",
    bodyPart: "Obliques & Transverse",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Assis au sol, buste penché en arrière à 45°, pieds décollés ou posés. Pivoter l'haltère de gauche à droite.",
    kineTips: "Tourner avec les épaules et la cage thoracique, pas seulement avec les bras.",
    iconName: "Target",
  },

  // ==========================================
  // BARRE & POIDS LIBRES SUPPLÉMENTAIRES
  // ==========================================
  {
    id: "exo-bar-1",
    name: "Développé Couché Prise Serrée (Barre)",
    category: "Bras",
    bodyPart: "Triceps & Centre Pectoraux",
    equipment: "Barre",
    trackingType: "weight_reps",
    defaultRestSeconds: 75,
    instructions: "Mains espacées de la largeur des épaules sur la barre. Descendre en gardant les coudes près du corps.",
    kineTips: "Cible le triceps tout en ménageant les deltoïdes antérieurs.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-bar-2",
    name: "Soulevé de Terre Sumo (Barre)",
    category: "Hanche",
    bodyPart: "Fessiers, Adducteurs & Ischios",
    equipment: "Barre",
    trackingType: "weight_reps",
    defaultRestSeconds: 90,
    instructions: "Pieds très écartés vers l'extérieur, mains à l'intérieur des genoux. Pousser le sol pour décoller la barre.",
    kineTips: "Position plus verticale du buste diminuant les contraintes de cisaillement lombaire.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-bar-3",
    name: "Good Morning à la Barre",
    category: "Dos & Tronc",
    bodyPart: "Chaîne Postérieure & Ischios",
    equipment: "Barre",
    trackingType: "weight_reps",
    defaultRestSeconds: 75,
    instructions: "Barre sur les trapèzes, genoux déverrouillés. Fléchir les hanches vers l'arrière en maintenant le dos droit.",
    kineTips: "Commencer avec une barre à vide pour maîtriser la charnière de hanche.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-bar-4",
    name: "Front Squat (Squat Avant Barre)",
    category: "Genou",
    bodyPart: "Quadriceps & Gainage Thoracique",
    equipment: "Barre",
    trackingType: "weight_reps",
    defaultRestSeconds: 90,
    instructions: "Barre posée sur les deltoïdes antérieurs, coudes hauts pointés vers l'avant. Descendre en squat vertical.",
    kineTips: "Recrute fortement les quadriceps et préserve la colonne lombaire grâce au buste droit.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-bar-5",
    name: "Shrugs Trapèzes à la Barre",
    category: "Dos & Tronc",
    bodyPart: "Trapèzes Supérieurs",
    equipment: "Barre",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Debout barre devant les cuisses en pronation. Hausser les épaules sans plier les bras.",
    kineTips: "Garder la tête neutre, ne pas avancer le menton.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-bar-6",
    name: "Développé Incliné à la Barre",
    category: "Pectoraux & Dos",
    bodyPart: "Haut des Pectoraux",
    equipment: "Barre",
    trackingType: "weight_reps",
    defaultRestSeconds: 90,
    instructions: "Banc incliné à 30°, descendre la barre sous la clavicule et développer de manière explosive.",
    kineTips: "Éviter les rebonds sur la cage thoracique.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-bar-7",
    name: "Floor Press à la Barre (Développé Couché au Sol)",
    category: "Pectoraux & Dos",
    bodyPart: "Pectoraux & Triceps (Angle sécurisé)",
    equipment: "Barre",
    trackingType: "weight_reps",
    defaultRestSeconds: 75,
    instructions: "Allongé sur le dos au sol, genoux pliés. Descendre la barre jusqu'à ce que les triceps touchent le sol.",
    kineTips: "Le sol stoppe l'hyperextension de l'épaule. Idéal après instabilité ou chirurgie acromiale.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-bar-8",
    name: "Curl Barre Droite en Supination",
    category: "Bras",
    bodyPart: "Biceps Brachial",
    equipment: "Barre",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Debout, paumes vers le haut, fléchir les coudes pour monter la barre vers le torse.",
    kineTips: "Si les poignets tiraillent, préférer la barre EZ courbée.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-bar-9",
    name: "Fentes Avant Fixes à la Barre",
    category: "Genou",
    bodyPart: "Quadriceps & Fessiers",
    equipment: "Barre",
    trackingType: "weight_reps",
    defaultRestSeconds: 75,
    instructions: "Barre sur les trapèzes, une jambe avancée, descendre le bassin vers le sol puis remonter.",
    kineTips: "Stabiliser le pied avant à plat au sol sans décoller le talon.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-bar-10",
    name: "Hip Thrust à la Barre Guidée",
    category: "Hanche",
    bodyPart: "Grand Fessier (Isolation)",
    equipment: "Barre",
    trackingType: "weight_reps",
    defaultRestSeconds: 75,
    instructions: "Haut du dos sur un banc, barre guidée avec coussin sur le bassin. Pousser avec les fessiers vers le haut.",
    kineTips: "Verrouiller en rétroversion du bassin au sommet du mouvement.",
    iconName: "Dumbbell",
  },

  // ==========================================
  // KETTLEBELLS SUPPLÉMENTAIRES
  // ==========================================
  {
    id: "exo-kb-1",
    name: "Kettlebell Snatch (Arraché Unilatéral)",
    category: "Dos & Tronc",
    bodyPart: "Chaîne Postérieure & Épaules",
    equipment: "Kettlebell",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "D'un mouvement explosif de hanche, propulser la kettlebell directement au-dessus de la tête.",
    kineTips: "Exercice avancé de puissance et coordination neuromusculaire.",
    iconName: "Target",
  },
  {
    id: "exo-kb-2",
    name: "Kettlebell Goblet Lunge",
    category: "Genou",
    bodyPart: "Quadriceps, Fessiers & Stabilité",
    equipment: "Kettlebell",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Kettlebell tenue contre la poitrine à deux mains. Effectuer des fentes alternées avec un tronc vertical.",
    kineTips: "Renforce la proprioception du genou en charge antérieure.",
    iconName: "Target",
  },
  {
    id: "exo-kb-3",
    name: "Kettlebell Deadlift Unilatéral (Single Leg RDL)",
    category: "Hanche",
    bodyPart: "Ischio-jambiers, Fessiers & Équilibre Cheville",
    equipment: "Kettlebell",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "En appui sur une jambe, descendre la kettlebell vers le sol en étendant la jambe arrière.",
    kineTips: "L'un des meilleurs exercices de prévention de récidive du ligament croisé antérieur (LCA).",
    iconName: "Compass",
  },
  {
    id: "exo-kb-4",
    name: "Kettlebell Windmill (Moulin à Vent)",
    category: "Dos & Tronc",
    bodyPart: "Obliques, Épaules & Mobilité Hamstrings",
    equipment: "Kettlebell",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Kettlebell bras tendu au-dessus de la tête. Fléchir la hanche latéralement pour toucher le pied opposé au sol.",
    kineTips: "Regarder toujours la kettlebell vers le haut pour stabiliser l'épaule.",
    iconName: "Target",
  },
  {
    id: "exo-kb-5",
    name: "Kettlebell Bottoms-Up Press",
    category: "Épaule",
    bodyPart: "Stabilisateurs Épaule & Grip",
    equipment: "Kettlebell",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Tenir la kettlebell à l'envers (base vers le haut). Développer verticalement en maintenant l'équilibre parfait.",
    kineTips: "Active puissamment la coiffe des rotateurs par réflexe proprioceptif.",
    iconName: "Target",
  },
  {
    id: "exo-kb-6",
    name: "Kettlebell Suitcase Carry (Marche Valise)",
    category: "Dos & Tronc",
    bodyPart: "Anti-Flexion Latérale & Rachis",
    equipment: "Kettlebell",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Marcher fièrement en portant une kettlebell lourde d'un seul côté, sans pencher le buste.",
    kineTips: "Travail du carré des lombes et du transverse pour protéger les disques vertébraux.",
    iconName: "Target",
  },
  {
    id: "exo-kb-7",
    name: "Kettlebell Gorilla Row",
    category: "Dos & Tronc",
    bodyPart: "Dorsaux, Rhomboïdes & Ischios",
    equipment: "Kettlebell",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Deux kettlebells au sol entre les pieds en position de squat large. Tirer alternativement une kettlebell vers la hanche.",
    kineTips: "Gainage isométrique puissant des lombaires et des jambes pendant le tirage.",
    iconName: "Target",
  },
  {
    id: "exo-kb-8",
    name: "Kettlebell Thruster",
    category: "Genou",
    bodyPart: "Full-Body (Quadriceps, Fessiers & Épaules)",
    equipment: "Kettlebell",
    trackingType: "weight_reps",
    defaultRestSeconds: 75,
    instructions: "Squat complet avec kettlebells aux épaules, puis extension explosive pour développer les charges au-dessus de la tête.",
    kineTips: "Coordination chaîne cinétique fermée vers chaîne ouverte.",
    iconName: "Target",
  },

  // ==========================================
  // POULIES & CÂBLES SUPPLÉMENTAIRES
  // ==========================================
  {
    id: "exo-poul-1",
    name: "Écarté Poulie Bas vers Haut (Upper Chest Crossover)",
    category: "Pectoraux & Dos",
    bodyPart: "Haut des Pectoraux (Claviculaire)",
    equipment: "Poulie",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Poulies réglées en position basse. Ramener les poignées vers le haut et l'intérieur en arc de cercle.",
    kineTips: "Excellente alternative sécurisée au développé incliné lourd.",
    iconName: "Target",
  },
  {
    id: "exo-poul-2",
    name: "Extension Triceps Unilatérale à la Poulie",
    category: "Bras",
    bodyPart: "Triceps (Isolation)",
    equipment: "Poulie",
    trackingType: "weight_reps",
    defaultRestSeconds: 45,
    instructions: "Un seul bras à la fois sans poignée ou avec cordelette. Tendre l'avant-bras vers le bas.",
    kineTips: "Corrige les asymétries de force droite/gauche.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-poul-3",
    name: "Curl Biceps à la Poulie Basse",
    category: "Bras",
    bodyPart: "Biceps (Tension Continue)",
    equipment: "Poulie",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Barre droite ou poignée à la poulie basse. Fléchir les bras en maintenant la tension constante.",
    kineTips: "Tension articulaire très douce en début de mouvement.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-poul-4",
    name: "Pallof Press Anti-Rotation (Poulie)",
    category: "Dos & Tronc",
    bodyPart: "Transverse, Obliques & Stabilité Lombaire",
    equipment: "Poulie",
    trackingType: "weight_reps",
    defaultRestSeconds: 45,
    instructions: "Debout de profil à la poulie, poignée tenue à deux mains contre la poitrine. Tendre les bras devant soi sans tourner le buste.",
    kineTips: "Le gold-standard de la rééducation du rachis et de la stabilité lombo-pelvienne.",
    iconName: "Target",
  },
  {
    id: "exo-poul-5",
    name: "Kickback Fessier à la Poulie Basse",
    category: "Hanche",
    bodyPart: "Grand Fessier",
    equipment: "Poulie",
    trackingType: "weight_reps",
    defaultRestSeconds: 45,
    instructions: "Sangle de cheville à la poulie basse. Pousser la jambe vers l'arrière en contractant le fessier.",
    kineTips: "Ne pas creuser le bas du dos à la fin de l'extension de hanche.",
    iconName: "Target",
  },
  {
    id: "exo-poul-6",
    name: "Abduction Hanche à la Poulie Basse",
    category: "Hanche",
    bodyPart: "Moyen Fessier & Stabilisateur Bassin",
    equipment: "Poulie",
    trackingType: "weight_reps",
    defaultRestSeconds: 45,
    instructions: "Debout de profil, écarter la jambe extérieure sur le côté en contrôlant le retour.",
    kineTips: "Renforce le moyen fessier pour contrer le valgus dynamique du genou.",
    iconName: "Target",
  },
  {
    id: "exo-poul-7",
    name: "Woodchopper / Bûcheron Rotatoire (Poulie)",
    category: "Dos & Tronc",
    bodyPart: "Obliques & Chaîne Spirale",
    equipment: "Poulie",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Poulie haute, tirer en diagonale vers la hanche opposée en accompagnant avec le pivot du pied arrière.",
    kineTips: "Transfère la force des hanches vers le haut du corps en rotation sportive.",
    iconName: "Target",
  },
  {
    id: "exo-poul-8",
    name: "Tirage Menton à la Poulie Basse (Upright Row)",
    category: "Épaule",
    bodyPart: "Deltoïde Latéral & Trapèzes",
    equipment: "Poulie",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Tirer la barre vers le sternum en montant les coudes vers le haut et l'extérieur.",
    kineTips: "S'arrêter au niveau du sternum pour ne pas pincer la bourse sous-acromiale.",
    iconName: "Target",
  },

  // ==========================================
  // RÉÉDUCATION KINÉ & MOBILITÉ SPÉCIFIQUE
  // ==========================================
  {
    id: "exo-poids-1",
    name: "Nordic Hamstring Curl Assisté",
    category: "Genou",
    bodyPart: "Ischio-jambiers (Excentrique Prévention LCA)",
    equipment: "Poids de corps",
    trackingType: "weight_reps",
    defaultRestSeconds: 75,
    instructions: "À genoux, chevilles bloquées ou tenues. Freiner la descente vers l'avant le plus lentement possible.",
    kineTips: "L'exercice numéro 1 pour la prévention des récidives sur greffe DIDT / LCA.",
    iconName: "Activity",
  },
  {
    id: "exo-poids-2",
    name: "Tibialis Raise contre un Mur",
    category: "Cheville & Pied",
    bodyPart: "Jambier Antérieur & Prévention Périostite",
    equipment: "Poids de corps",
    trackingType: "weight_reps",
    defaultRestSeconds: 45,
    instructions: "Dos calé contre un mur, talons au sol à 30cm du mur. Relever les pointes de pieds vers les tibias.",
    kineTips: "Amortit les chocs à la course et stabilise la cheville.",
    iconName: "Activity",
  },
  {
    id: "exo-poids-3",
    name: "Monster Walk avec Élastique aux Chevilles",
    category: "Hanche",
    bodyPart: "Moyen Fessier & Contrôle Genou Valgus",
    equipment: "Élastique",
    trackingType: "elastic_reps",
    defaultRestSeconds: 45,
    instructions: "Élastique autour des chevilles, demi-squat. Marcher en crabe ou en diagonale en maintenant la tension.",
    kineTips: "Garder les genoux écartés alignés avec les orteils.",
    iconName: "Activity",
  },
  {
    id: "exo-poids-4",
    name: "Squat Isométrique avec Ballon entre les Genoux",
    category: "Genou",
    bodyPart: "Quadriceps & Vaste Interne (VMO)",
    equipment: "Poids de corps",
    trackingType: "time",
    defaultRestSeconds: 45,
    instructions: "Dos au mur à 60° de flexion, ballon souple entre les genoux. Serrer le ballon en maintenant la position.",
    kineTips: "Stimule le vaste médial pour recentrer la rotule dans sa trochlée.",
    iconName: "Activity",
  },
  {
    id: "exo-poids-5",
    name: "Pompes Prise Diamant",
    category: "Bras",
    bodyPart: "Triceps & Pectoraux",
    equipment: "Poids de corps",
    trackingType: "reps_only",
    defaultRestSeconds: 60,
    instructions: "Mains rapprochées sous la poitrine, pouces et index formant un triangle. Descendre et repousser.",
    kineTips: "Possibilité de le faire sur les genoux en phase de réadaptation.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-poids-6",
    name: "Chin-ups Prise Supination",
    category: "Dos & Tronc",
    bodyPart: "Biceps & Grand Dorsal",
    equipment: "Poids de corps",
    trackingType: "reps_only",
    defaultRestSeconds: 90,
    instructions: "Suspendu à la barre en supination (paumes vers soi). Tirer jusqu'à passer le menton au-dessus de la barre.",
    kineTips: "Contrôler la descente sans relâcher brutalement les épaules.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-poids-7",
    name: "Cat-Cow / Chat-Vache Mobilité Rachis",
    category: "Mobilité & Étirement",
    bodyPart: "Rachis Lombaire & Thoracique",
    equipment: "Poids de corps",
    trackingType: "time",
    defaultRestSeconds: 30,
    instructions: "À quatre pattes, alterner dos rond en expirant et dos creux contrôlé en inspirant.",
    kineTips: "Mobilisation douce de chaque vertèbre sans forcer sur les butées articulaires.",
    iconName: "Compass",
  },
  {
    id: "exo-poids-8",
    name: "World's Greatest Stretch (Fente Torsadée)",
    category: "Mobilité & Étirement",
    bodyPart: "Hanche, Thoracique & Ischios",
    equipment: "Poids de corps",
    trackingType: "time",
    defaultRestSeconds: 30,
    instructions: "Fente profonde avant, poser la main opposée au sol et ouvrir le bras côté jambe avant vers le ciel.",
    kineTips: "Libère la mobilité thoracique et ouvre la hanche.",
    iconName: "Compass",
  },
];

// Clean slate: no pre-created routines or mock workouts!
export const DEFAULT_ROUTINES: Routine[] = [];
export const DEFAULT_WORKOUT_HISTORY: WorkoutSession[] = [];
