import { Exercise, Routine, UserProfile, WorkoutSession } from "./types";

export const DEFAULT_USERS: UserProfile[] = [
  {
    id: "kine-anais",
    name: "Anaïs",
    email: "anais.kine@redreeduc.fr",
    role: "KINE",
    clinicName: "Cabinet de Kinésithérapie du Sport",
  },
  {
    id: "patient-reda",
    name: "Reda",
    email: "reda@redreeduc.fr",
    role: "PATIENT",
    kineId: "kine-anais",
    diagnosis: "Rupture du LCA genou droit (Post-opératoire)",
    medicalHistory: "Ligamentoplastie DIDT effectuée il y a 3 mois.",
    targetGoals: "Récupérer la stabilité et la force du quadriceps sans douleur fémoro-patellaire > 3/10. Reprise du footing.",
  },
];

export const DEFAULT_EXERCISES: Exercise[] = [
  // --- GENOU & MEMBRES INFÉRIEURS ---
  {
    id: "exo-genou-1",
    name: "Chaise au Mur (Isométrie Quadriceps)",
    category: "Genou",
    bodyPart: "Quadriceps & Fessiers",
    equipment: "Poids de corps / Mur",
    trackingType: "time",
    defaultRestSeconds: 60,
    instructions: "Dos plaqué contre le mur, genoux fléchis à 90°, pieds écartés de la largeur du bassin. Maintenir la position.",
    kineTips: "Veillez à ce que les genoux ne dépassent pas la pointe des pieds. Stop immédiat si douleur rotulienne.",
    iconName: "Shield",
  },
  {
    id: "exo-genou-2",
    name: "Pont Fessier Unipodal (Glute Bridge)",
    category: "Genou",
    bodyPart: "Grand Fessier & Ischios",
    equipment: "Poids de corps",
    trackingType: "reps_only",
    defaultRestSeconds: 45,
    instructions: "Allongé sur le dos, une jambe pliée au sol, l'autre tendue dans l'alignement. Pousser sur le talon pour monter le bassin.",
    kineTips: "Conserver le bassin bien horizontal lors de la montée, ne pas cambrer le bas du dos.",
    iconName: "Activity",
  },
  {
    id: "exo-genou-3",
    name: "Presse à Cuisses (Contrôlée)",
    category: "Genou",
    bodyPart: "Quadriceps, Fessiers",
    equipment: "Machine",
    trackingType: "weight_reps",
    defaultRestSeconds: 90,
    instructions: "Pieds écartés largeur d'épaules sur le plateau. Descente contrôlée en 3 secondes, poussée dynamique sans verrouiller les genoux.",
    kineTips: "Descente à 80-90° max de flexion. Conserver les genoux alignés avec le 2ème orteil.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-genou-4",
    name: "Proprioception sur Plateau de Freeman",
    category: "Cheville & Pied",
    bodyPart: "Cheville, Genou & Stabilisateurs",
    equipment: "Plateau d'équilibre",
    trackingType: "time",
    defaultRestSeconds: 45,
    instructions: "En appui sur un seul pied au centre du plateau d'équilibre. Maintenir le plateau le plus horizontal possible sans toucher le sol.",
    kineTips: "Fixer un point au loin. Léger déverrouillage du genou recommandé.",
    iconName: "Compass",
  },
  {
    id: "exo-genou-5",
    name: "Fente Contrôlée avec Haltères",
    category: "Genou",
    bodyPart: "Quadriceps, Fessiers, Ischios",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Un grand pas en avant, descendre le genou arrière vers le sol à angle droit. Remonter en poussant sur le talon avant.",
    kineTips: "Contrôler la phase descendante. Le genou avant doit rester stable sans rentrer vers l'intérieur.",
    iconName: "Flame",
  },
  {
    id: "exo-genou-6",
    name: "Leg Extension Unilatéral (Guidé)",
    category: "Genou",
    bodyPart: "Vaste Interne & Droit Antérieur",
    equipment: "Machine",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Assis sur la machine, dos calé. Extension de la jambe blessée en concentrique 2s, maintien 1s en haut, descente 3s.",
    kineTips: "Limiter l'amplitude aux 45 derniers degrés pour épargner le greffon LCA selon protocole.",
    iconName: "Zap",
  },
  {
    id: "exo-genou-7",
    name: "Clamshell avec Élastique",
    category: "Hanche",
    bodyPart: "Moyen Fessier",
    equipment: "Élastique",
    trackingType: "elastic_reps",
    defaultRestSeconds: 45,
    instructions: "Couché sur le côté, genoux fléchis à 90°, élastique autour des genoux. Ouvrir le genou supérieur en gardant les pieds collés.",
    kineTips: "Le bassin ne doit pas basculer vers l'arrière.",
    iconName: "Repeat",
  },

  // --- ÉPAULE & COIFFE DES ROTATEURS ---
  {
    id: "exo-epaule-1",
    name: "Rotateurs Externes à l'Élastique",
    category: "Épaule",
    bodyPart: "Sous-épineux & Petit Rond",
    equipment: "Élastique",
    trackingType: "elastic_reps",
    defaultRestSeconds: 60,
    instructions: "Coude collé au corps fléchi à 90°, une serviette roulée sous le bras. Tirer l'élastique vers l'extérieur sans décoller le coude.",
    kineTips: "Mouvement lent et fluide, serrer légèrement les omoplates vers le bas.",
    iconName: "RotateCw",
  },
  {
    id: "exo-epaule-2",
    name: "Wall Slide (Glissement Scapulaire au Mur)",
    category: "Épaule",
    bodyPart: "Dentelé Antérieur & Trapèze Inférieur",
    equipment: "Poids de corps / Mur",
    trackingType: "reps_only",
    defaultRestSeconds: 45,
    instructions: "Avant-bras en contact avec le mur en 'W'. Faire glisser les bras vers le haut en forme de 'Y' sans décoller le contact.",
    kineTips: "Ne pas cambrer la région lombaire, garder les côtes rentrées.",
    iconName: "ArrowUp",
  },
  {
    id: "exo-epaule-3",
    name: "Élévation Latérale (Haltère)",
    category: "Épaule",
    bodyPart: "Deltoïde Moyen",
    equipment: "Haltère",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Debout, un haltère dans chaque main. Élever les bras sur les côtés jusqu'à hauteur d'épaules dans le plan scapulaire (30° vers l'avant).",
    kineTips: "Ne pas hausser les épaules (garder les trapèzes relâchés).",
    iconName: "Dumbbell",
  },
  {
    id: "exo-epaule-4",
    name: "Oiseau Buste Appuyé (Haltère)",
    category: "Épaule",
    bodyPart: "Deltoïde Postérieur & Rhomboïdes",
    equipment: "Haltère & Banc",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Buste appuyé sur banc incliné à 30-45°, coudes légèrement fléchis. Écarter les bras vers l'extérieur en serrant les omoplates.",
    kineTips: "Excellent pour corriger la posture enroulée des épaules.",
    iconName: "Eye",
  },

  // --- BRAS & COUDE ---
  {
    id: "exo-bras-1",
    name: "Curl Biceps (Haltère)",
    category: "Bras",
    bodyPart: "Biceps Brachial",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Debout ou assis, coudes fixés au niveau des flancs. Fléchir l'avant-bras en effectuant une supination complète du poignet.",
    kineTips: "Contrôler la descente sans balancer le buste.",
    iconName: "Dumbbell",
  },
  {
    id: "exo-bras-2",
    name: "Curl Marteau (Haltère)",
    category: "Bras",
    bodyPart: "Brachio-radial & Long Supinateur",
    equipment: "Haltères",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Prise neutre (pouces vers le haut). Monter l'haltère de façon stricte sans rotation du poignet.",
    kineTips: "Renforce la stabilité de l'avant-bras et du coude.",
    iconName: "Hammer",
  },

  // --- DOS, RACHIS & GAINAGE ---
  {
    id: "exo-dos-1",
    name: "Gainage Planche Ventrale",
    category: "Dos & Tronc",
    bodyPart: "Transverse & Sangle Abdominale",
    equipment: "Poids de corps / Tapis",
    trackingType: "time",
    defaultRestSeconds: 60,
    instructions: "En appui sur les avant-bras et la pointe des pieds. Maintenir le corps rectiligne, nombril aspiré vers la colonne.",
    kineTips: "Ne pas creuser les lombaires ni lever les fesses trop haut. Respiration fluide.",
    iconName: "Shield",
  },
  {
    id: "exo-dos-2",
    name: "Bird Dog (Chien d'Arrêt Croisé)",
    category: "Dos & Tronc",
    bodyPart: "Érecteurs du Rachis, Fessiers, Transverse",
    equipment: "Poids de corps / Tapis",
    trackingType: "reps_only",
    defaultRestSeconds: 45,
    instructions: "À quatre pattes, tendre simultanément le bras droit devant et la jambe gauche derrière. Maintenir 3 secondes puis alterner.",
    kineTips: "Le bassin et les épaules restent parfaitement horizontaux.",
    iconName: "Smile",
  },

  // --- CHEVILLE, PIED & CARDIO ---
  {
    id: "exo-cheville-1",
    name: "Mollets Debout sur Marche (Calf Raises)",
    category: "Cheville & Pied",
    bodyPart: "Triceps Sural & Tendon d'Achille",
    equipment: "Marche / Step",
    trackingType: "weight_reps",
    defaultRestSeconds: 60,
    instructions: "Avant-pied sur la marche, talons dans le vide. Montée maximale sur la pointe des pieds, descente lente sous le niveau du step.",
    kineTips: "Temps d'arrêt de 2 secondes en bas pour solliciter le tendon d'Achille.",
    iconName: "TrendingUp",
  },
  {
    id: "exo-cardio-1",
    name: "Tapis de Course (Marche / Course)",
    category: "Cardio & Échauffement",
    bodyPart: "Système Cardio-Vasculaire & Membres Inférieurs",
    equipment: "Tapis de Course",
    trackingType: "distance_time",
    defaultRestSeconds: 0,
    instructions: "Marche rapide inclinée ou course contrôlée selon l'état du genou / de la cheville.",
    kineTips: "Attaque médio-pied, cadence fluide, sans boiterie.",
    iconName: "Footprints",
  },
  {
    id: "exo-cardio-2",
    name: "Vélo Stationnaire (Rodage Articulaire)",
    category: "Cardio & Échauffement",
    bodyPart: "Genoux & Hanche (Mobilisation)",
    equipment: "Vélo d'appartement",
    trackingType: "time",
    defaultRestSeconds: 0,
    instructions: "Pédalage à résistance modérée (60-80 RPM) pour chauffer le cartilage et mobiliser l'articulation en douceur.",
    kineTips: "Selle réglée à hauteur de hanche pour éviter une flexion excessive du genou.",
    iconName: "Bike",
  },
];

// Clean slate: no pre-created routines or mock workouts!
export const DEFAULT_ROUTINES: Routine[] = [];
export const DEFAULT_WORKOUT_HISTORY: WorkoutSession[] = [];
